In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch

In [3]:
scalar = torch.tensor(1) #scalars and 1D vectors in lower case
print(scalar)
print(scalar.item())
print(scalar.ndim)

tensor(1)
1
0


In [4]:
MATRIX = torch.tensor([[1,2],[3,4]]) #matrices and high dim tensors are wrtten in upper case
print(MATRIX)
print(MATRIX.ndim)

tensor([[1, 2],
        [3, 4]])
2


In [5]:
print(MATRIX.shape)

torch.Size([2, 2])


In [6]:
RANDOM = torch.rand(3,4,3)
print(RANDOM)
print(RANDOM.ndim)

tensor([[[0.9070, 0.4892, 0.1622],
         [0.2222, 0.5335, 0.8293],
         [0.5031, 0.1738, 0.6691],
         [0.6664, 0.6454, 0.1740]],

        [[0.6131, 0.0552, 0.6369],
         [0.6695, 0.4656, 0.7826],
         [0.6606, 0.7450, 0.1798],
         [0.5031, 0.3684, 0.3854]],

        [[0.7163, 0.8794, 0.7085],
         [0.4234, 0.2433, 0.7918],
         [0.0416, 0.0891, 0.3161],
         [0.1867, 0.3625, 0.7666]]])
3


In [7]:
RAND_IMG_TENSOR = torch.rand(size=(224,224,3))
print(RAND_IMG_TENSOR)
print(RAND_IMG_TENSOR.ndim)
print(RAND_IMG_TENSOR.shape)

tensor([[[0.2896, 0.7857, 0.9395],
         [0.4712, 0.9241, 0.9057],
         [0.4841, 0.6851, 0.6509],
         ...,
         [0.2062, 0.8078, 0.4407],
         [0.4903, 0.5301, 0.8340],
         [0.4233, 0.2678, 0.4779]],

        [[0.9598, 0.2046, 0.1271],
         [0.5539, 0.2347, 0.3341],
         [0.5066, 0.8178, 0.1967],
         ...,
         [0.5646, 0.3034, 0.1577],
         [0.5163, 0.9303, 0.3446],
         [0.6087, 0.5435, 0.8107]],

        [[0.8611, 0.2656, 0.2036],
         [0.9853, 0.3110, 0.7032],
         [0.0333, 0.2072, 0.8296],
         ...,
         [0.3191, 0.7189, 0.6924],
         [0.0189, 0.3339, 0.1611],
         [0.8733, 0.1079, 0.9002]],

        ...,

        [[0.0638, 0.8229, 0.5160],
         [0.6293, 0.5627, 0.3946],
         [0.7622, 0.7400, 0.7355],
         ...,
         [0.8897, 0.2462, 0.0143],
         [0.9816, 0.8043, 0.8908],
         [0.0179, 0.0937, 0.3903]],

        [[0.0063, 0.0650, 0.0997],
         [0.1438, 0.0011, 0.4325],
         [0.

In [8]:
ZEROES = torch.zeros(size=(3,4))
print(ZEROES)
print(ZEROES.ndim)

ONES = torch.ones(size=(3,4))
print(ONES)
print(ONES.ndim)
print(ONES.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
2
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
2
torch.float32


In [9]:
RANGE = torch.arange(start=0, end = 10, step=2)
print(RANGE)

tensor([0, 2, 4, 6, 8])


In [10]:
LIKE_RANGE = torch.zeros_like(input=RANGE)
print(LIKE_RANGE)

tensor([0, 0, 0, 0, 0])


In [11]:
#Tensor DATA TYPES
# 3 Errors in Torch:
# 1. Tensors not right datatype
# 2. Tensors not right shape
# 3. Tensors not on the right device

float32_type = torch.tensor(data =[1,2,3],
                         dtype=torch.float32,
                         device="cpu",    #cpu, cuda, NONE
                         requires_grad=False)
print(float32_type)
float_16= float32_type.type(torch.float16)
print(float_16)


tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float16)


In [12]:
float_16 * float32_type

tensor([1., 4., 9.])

In [13]:
%%time
A = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.long)
B = torch.tensor([[7,8],[9,10],[11,12]], dtype=torch.long)
print(torch.matmul(A,B))
print(A.T@B.T)

tensor([[ 58,  64],
        [139, 154]])
tensor([[ 39,  49,  59],
        [ 54,  68,  82],
        [ 69,  87, 105]])
CPU times: user 3.88 ms, sys: 0 ns, total: 3.88 ms
Wall time: 13.2 ms


In [14]:
A = torch.tensor([1,2,3,4,5,6])
print(A.argmin(), A.argmax())

tensor(0) tensor(5)


In [15]:
#reshaping, stacking, squeezing, unsqueezing
A_reshape = A.reshape(3,2)
print(A_reshape)

A_reshape = A.view(2,3)
A_reshape

A_stack = torch.stack([A,A,A,A], dim=0)
print(A_stack)


A_stack = torch.stack([A,A,A,A], dim=1)
print(A_stack)

W = torch.tensor([[1,2,3],[4,5,6]])
W_stack = torch.stack([W,W,W,W], dim=2)
print(W_stack)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6]])
tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3]],

        [[4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6]]])


In [16]:
sq = torch.tensor([[1,2,3,4,4]])
print(sq.shape)
print(sq.squeeze().shape)
# torch.tensor([[1,2,3,4,4]]).shape,torch.tensor([[1,2,3,4,4]]).squeeze().shape

unsq = torch.tensor([1,2,3,4,5])
print(unsq.shape)
print(unsq.unsqueeze(dim=0).shape)
print(unsq.unsqueeze(dim=1).shape)

torch.Size([1, 5])
torch.Size([5])
torch.Size([5])
torch.Size([1, 5])
torch.Size([5, 1])


In [17]:
#combining torch with NUmpy

import numpy as np
arr = np.array([[1,2,3],[4,5,6]]) #default in float64
torch_tensor = torch.from_numpy(arr) #results in float64 tensor
print(arr)
print(torch.from_numpy(arr), torch_tensor.dtype)
print(torch_tensor.numpy())
#Changes in original np array will not change tensor and vice versa

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]]) torch.int64
[[1 2 3]
 [4 5 6]]


In [18]:
#saving tensors on CPU vs GPU
ts = torch.tensor([1,2,3,4,5], device='cpu')
#use .to_cpu() .to_gpu() to switch, numpy arrays can compute only on cpus
print(ts, ts.device)

tensor([1, 2, 3, 4, 5]) cpu


In [19]:
!pwd

/content
